// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gx_test_other.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace gx_test_other {

  #region Messages
  public sealed class gx_data_other : pb::IMessage {
    private static readonly pb::MessageParser<gx_data_other> _parser = new pb::MessageParser<gx_data_other>(() => new gx_data_other());
    public static pb::MessageParser<gx_data_other> Parser { get { return _parser; } }

    private float sc_float_;
    public float sc_float {
      get { return sc_float_; }
      set {
        sc_float_ = value;
      }
    }

    private int sc_int32_;
    public int sc_int32 {
      get { return sc_int32_; }
      set {
        sc_int32_ = value;
      }
    }

    private string sc_string_ = "";
    public string sc_string {
      get { return sc_string_; }
      set {
        sc_string_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (sc_float != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(sc_float);
      }
      if (sc_int32 != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(sc_int32);
      }
      if (sc_string.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(sc_string);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (sc_float != 0F) {
        size += 1 + 4;
      }
      if (sc_int32 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(sc_int32);
      }
      if (sc_string.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(sc_string);
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 21: {
            sc_float = input.ReadFloat();
            break;
          }
          case 24: {
            sc_int32 = input.ReadInt32();
            break;
          }
          case 50: {
            sc_string = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
